name: Integration

on:
  pull_request:
  push:
    paths-ignore:
      - '**.md'
    branches:
      - main
      - release/*

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    steps:
      - uses: actions/checkout@v4
      - uses: technote-space/get-diff-action@v6.1.2
        with:
          PATTERNS: |
            **/*.go
            **/*.plush
            go.mod
            go.sum
            **/testdata/**

      - uses: actions/setup-go@v5
        if: env.GIT_DIFF
        with:
          go-version: "1.22"
          cache: true
          cache-dependency-path: go.sum

      - name: Run integration
        run: go test -race -failfast -v -timeout 120m ./integration/...
        if: env.GIT_DIFF
